module.exports = {
	indent: ['error', 'tab'],
	singleQuote: true,
	semi: true,
	useTabs: true,
	tabWidth: 2,
	printWidth: 80,
	trailingComma: 'es5',
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: 'avoid',
	vueIndentScriptAndStyle: false,
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: false,
	proseWrap: 'preserve',
	quoteProps: 'as-needed',
	requirePragma: false,
	endOfLine: 'auto',
	embeddedLanguageFormatting: 'auto',
};
